<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="MelodicMetalReviews.Default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
  <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
  <asp:GridView ID="GridView1" runat="server" DataKeyNames="AlbumID" ItemType="MelodicMetalReviews.Models.Album"
     SelectMethod="GetAlbums" UpdateMethod="UpdateAlbum" DeleteMethod="DeleteAlbum"
     AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False">
    <Columns>
      <asp:HyperLinkField DataNavigateUrlFields="AlbumID" DataNavigateUrlFormatString="AddEdit.aspx?id={0}" DataTextField="AlbumName" HeaderText="Album Name" NavigateUrl="AddEditAlbum.aspx?id={0}" />
      <asp:DynamicField DataField="Rating" HeaderText="Rating" />
      <asp:DynamicField DataField="Review" HeaderText="Review" />
      <asp:TemplateField HeaderText="Band Name">
        <ItemTemplate>
          <asp:Label Text='<%# Eval("Band.BandName") %>' runat="server" />
        </ItemTemplate>
      </asp:TemplateField>
    </Columns>
  </asp:GridView>
</asp:Content>
